name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake Ep10
      run: |
        cd ${{github.workspace}}/Code-Tech-and-Tutorials/Ep10/
        cmake -B ${{github.workspace}}/Code-Tech-and-Tutorials/Ep10/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        
    - name: Build Ep10
      run: |
        cd ${{github.workspace}}/Code-Tech-and-Tutorials/Ep10/
        cmake --build ${{github.workspace}}/Code-Tech-and-Tutorials/Ep10/build --config ${{env.BUILD_TYPE}}
        
    - name: Configure CMake EP03
      run: |
        sudo apt-get install xorg-dev libglu1-mesa-dev -y
        git submodule update --init --recursive
        cd ${{github.workspace}}/Code-Tech-and-Tutorials/EP03/
        cmake -B ${{github.workspace}}/Code-Tech-and-Tutorials/EP03/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGLFW_BUILD_DOCS=OFF
    
    - name: Build EP03
      run: |
        git submodule update --init --recursive
        cd ${{github.workspace}}/Code-Tech-and-Tutorials/EP03/
        cmake -B ${{github.workspace}}/Code-Tech-and-Tutorials/EP03/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DGLFW_BUILD_DOCS=OFF

